### ISSUE TITLE
KGEmbedding_Populate.ipynb failing with - ModuleNotFoundError: No module named 'openai.embeddings_utils'

### ISSUE THREAD

**Issue by nickcaine** [Joshua-Yu/graph-rag#1]
I believe OpenAI have reorganised their codebase in the latest version and am now getting the following error:

ModuleNotFoundError: No module named 'openai.embeddings_utils'

**Comment by Joshua-Yu** [comment]
Yes since OpenAI library 1.8 the embedding API has been changed. Submitted new code to be compatible.
