### ISSUE TITLE
Values of type <class 'openai.types.create_embedding_response.CreateEmbeddingResponse'> are not supported

### ISSUE THREAD

**Issue by pasindu-pr** [Joshua-Yu/graph-rag#2]
Hi,

So first I try ran  LayoutPDFReader_KGLoader.ipynb file. It was successfully loaded and now I see the data in the Neo4j database. And now I' trying to run the KGEmbedding_Populate.ipynb file. But when I invoke the LoadEmbedding function like this `LoadEmbedding("Chunk", "sentences")` it throws the following error. Do you have any idea, why is that happening?

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-9-9611401e81a0>](https://localhost:8080/#) in <cell line: 1>()
----> 1 LoadEmbedding("Table", "name")
      2 

11 frames
[/usr/local/lib/python3.10/dist-packages/neo4j/_codec/packstream/v1/__init__.py](https://localhost:8080/#) in _py_pack(self, value, dehydration_hooks)
    155                     return
    156 
--> 157             raise ValueError("Values of type %s are not supported" % type(value))
    158 
    159     def _pack_bytes_header(self, size):

ValueError: Values of type <class 'openai.types.create_embedding_response.CreateEmbeddingResponse'> are not supported`

**Comment by Joshua-Yu** [comment]
Yes there was a bug which I have just fixed. Can you download the code and try again?

**Comment by pasindu-pr** [comment]
Thanks a lot. It works now!
